name: Test build and commands with macOS-latest

on:
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1

    - name: Tell about the workflow
      if: github.event_name == 'pull_request'
      run: echo This event is a pull request. Test build ./ld init.

    - name: Check the current user's name and home folder path
      run: whoami

    - name: What shell is being used
      run: |
        echo $0
        ls -lha ~/.ba*

    - name: Verify virtualisation is supported
      run: sysctl kern.hv_support

    - name: Check Virtualbox path
      run: which virtualbox
      
    - name: Check lo0
      run: ifconfig lo0

    - name: Install docker, docker-compose, docker-machine, boot2docker{,-cli}
      run: |
        brew install docker
        brew install docker-compose
        brew install docker-machine
        brew install boot2docker boot2docker-cli

    - name: Check paths of docker-* binaries
      run: |
        echo -n 'docker installed in path: ' && which docker
        echo -n 'docker-compose installed in path: ' && which docker-compose
        echo -n 'docker-machine installed in path: ' && which docker-machine

    - name: Create image cache for Docker
      run: mkdir -p ~/.docker/machine/cache/
    
    - name: Download Boot2Docker iso image
      run: | 
        cd ~/.docker/machine/cache/
        curl -Lo boot2docker.iso https://github.com/boot2docker/boot2docker/releases/download/v19.03.5/boot2docker.iso
        ls -lha 
        file boot2docker.iso
        
    - name: Create machine with Virtualbox and start it
      run: |
        docker-machine ls
        echo "----"
        docker-machine create --driver virtualbox --virtualbox-boot2docker-url ~/.docker/machine/cache/boot2docker.iso default
        echo "----"
        docker-machine ls
        echo "----"
        docker-machine restart
        echo "----"
        docker-machine ls

    - name: Install docker-sync
      run: |
        gem install docker-sync --user-install
        GEMPATH=$HOME/.gem/ruby/2.6.0/bin
        echo "export PATH=\"\$PATH:$GEMPATH\"" >> ~/.bashrc # Bash
        source ~/.bashrc
        echo $PATH
        echo -n 'docker-sync installed in path: ' && which docker-sync
        docker-sync

    - name: List what is in the project folder.
      run: |
        pwd
        ls -lha
        file ld
        file ld.sh
 
    - name: Run help and see where it gets us
      run: ./ld

    - name: Run init and see where it gets us
      run: ./ld init
